#include"irq.h"


void button_init(void)
{
// active l horloge c 
  SET_BIT(RCC->AHB2ENR,RCC_AHB2ENR_GPIOCEN);
// je le port pc13 en mode sortie
  CLEAR_BIT(GPIOC->MODER,GPIO_MODER_MODE13_0);
  CLEAR_BIT(GPIOC->MODER,GPIO_MODER_MODE13_1);

// confert 14.3.4
  SET_BIT(EXTI->IMR1,EXTI_IMR1_IM13);

  SET_BIT(EXTI->RTSR1,EXTI_RTSR1_RT13);
 
  NVIC_EnableIRQ(EXTI15_10_IRQn);
  SET_BIT(SYSCFG->EXTICR[3],SYSCFG_EXTICR4_EXTI13_PC);
}



// Handler 
void  EXTI15_10_IRQn_Handler(void){

  SET_BIT(EXTI->PR1, EXTI_PR1_PIF13);
  SET_BIT(RCC->AHB2ENR,RCC_AHB2ENR_GPIOBEN);
  SET_BIT(GPIOB->MODER, GPIO_MODER_MODE14_0);
  CLEAR_BIT(GPIOB->MODER, GPIO_MODER_MODE14_1);

  if( READ_BIT(GPIOB->ODR,GPIO_ODR_OD14) ==0 ){
    SET_BIT(GPIOB->ODR,GPIO_ODR_OD14);
  }
  else{
    CLEAR_BIT(GPIOB->ODR,GPIO_ODR_OD14);
  }
}
